### ISSUE TITLE
Copying bundle outside of Phar

### ISSUE THREAD

**Issue by oschwald** [composer/ca-bundle#10]
Currently, if this package is used from a Phar file, the implementer needs to manually copy the CA bundle outside of the Phar file in order for the bundle to work with curl. Composer, for instance, [implements this functionality](https://github.com/composer/composer/blob/87fbf4a6cd633eefec82fb2568980c57ba0fb9a2/src/Composer/Util/RemoteFilesystem.php#L860). It would be nice if that functionality could be moved into this package so that other users would not need to reimplement it.

**Comment by Seldaek** [comment]
Feel free to send a PR to add the functionality here.

**Comment by alcohol** [comment]
> Currently, if this package is used from a Phar file

Is that not a choice of the end-user though (e.g. Composer is an end-user)?

Why should the functionality you describe be contained within this package/repository? It does not really seem to fit the scope of what we are offering here.

**Comment by oschwald** [comment]
My assumption was that most users of this package want a path to a CA bundle that they can pass to curl or another HTTP client and expect it to work. This is not the case currently. A library (e.g., a web service client API) writer using this package will either need to re-implement the temp-file functionality or force the users of their library to re-implement it and explicitly pass the cert if they are using the library within a Phar.

That said, I assumed that it was not included in this package for a reason, which is why I explicitly asked whether a PR would be accepted.

**Comment by alcohol** [comment]
> A library (e.g., a web service client API) writer using this package will either need to re-implement the temp-file functionality or force the users of their library to re-implement it and explicitly pass the cert if they are using the library within a Phar.

The first half of that statement is simply not true. I do not know where you are getting this from. Anyone using this package as a dependency of their own project can just copy the file path returned by it. You only have to use the special stream-copy method Composer uses if the following two conditions apply (`&&`, not `||`):

- you have to deal with PHP versions that include the bug it works around,
- you wrap/offer your application as a Phar.

**Comment by oschwald** [comment]
The whole statement was conditioned with "if [the end users] are using the library within a Phar." I apologize if that wasn't clear. I don't really want to argue this. If you don't feel like this belongs here, I am happy to close this issue. I just brought it up because Composer obviously has to implement this functionality, Guzzle used to have similar functionality when they distributed a CA bundle, and I know I had to do so as well in a library I maintain.

**Comment by alcohol** [comment]
@oschwald the bug I was referring to was the need to use the `stream_copy_to_stream` work-around, sorry if that was not clear.

**Comment by kelunik** [comment]
Why has this been closed? It's still unresolved. `amphp/socket` implemented a similar technique when it bundled a certificate file: https://github.com/amphp/socket/blob/7d82b194d970f832aef3b3b5b7c2bc393ba77b30/lib/functions.php#L186-L202

**Comment by oschwald** [comment]
I closed the issue as there was hostility towards including the functionality in this package. I agree that including it here would help prevent users of this package from having to reimplement it.

**Comment by Seldaek** [comment]
My first answer said please send a PR.. I don't see how that is hostile to having the feature :)

**Comment by oschwald** [comment]
@Seldaek, I was not referring to your response. :-) I've re-opened the issue.

**Comment by Seldaek** [comment]
Closed by #24
