### ISSUE TITLE
Consider using openssl_get_cert_locations

### ISSUE THREAD

**Issue by kelunik** [composer/ca-bundle#16]
It should be considered using http://php.net/openssl_get_cert_locations on newer versions (PHP 5.6+).

[Possible implementation](https://github.com/amphp/socket/blob/a31dd53aef57425d189a8a8c0a8fcafaf33b5607/lib/Internal/functions.php#L206-L220).

**Comment by Seldaek** [comment]
Sounds good if you wanna send a PR (don't forget we still support PHP 5.3 array syntax tho:) 

We already take care of the env vars though and using openssl.cafile/capath I am not sure if we already take care of the rest or if this really brings anything additional.

**Comment by exussum12** [comment]
As an update here, this was implemented and it looks like its a compile time setting not a run time one, so the path doesnt exist correctly on some systems.

This was removed as it started making curl check wrong locations
