### ISSUE TITLE
Ca-bundle missed new versions of Homebrew OSx

### ISSUE THREAD

**Issue by benbor** [composer/ca-bundle#51]
My Homebrew installs openssl with the following configuration:
```
➜  composer git:(d8aef3af) openssl version -d
OPENSSLDIR: "/usr/local/etc/openssl@1.1"
```
This path isn't included by default.
Does it make sense to add this path before https://github.com/composer/ca-bundle/blob/master/src/CaBundle.php#L94 ?

Or other option it is execute `openssl version -d` and add this path even automatically

Any ideas?

**Comment by Seldaek** [comment]
Seems like the next version of openssl is gonna be 3.0, that may be why homebrew switched current to this odd @1.1? I don't know, but anyway let's keep it as is for now, and see what comes up in the future.

**Comment by benbor** [comment]
> that may be why homebrew switched current to this odd @1.1
As I understand, "at sign" style became common for versioning in homebrew. 

But, anyway, @Seldaek  what do you think about execute `openssl version -d` at runtime and add gotten result to the `$otherLocations` ?  If you find this useful, I'll make PR

**Comment by Seldaek** [comment]
I see it might be more correct but this sounds rather undesirable tbh to execute an external process in the context of this lib, which is used in many other places, where I doubt they expect this amount of overhead.
