### ISSUE TITLE
class CaBundle does not extends from class Bundle -> BundleInterface

### ISSUE THREAD

**Issue by RicoFactset** [composer/ca-bundle#56]
Hi,

BundleInterface implements method getName():
```
    /**
     * Returns the bundle name (the class short name).
     *
     * @return string The Bundle name
     */
    public function getName();
```

The recipe adds an entry for CaBundle to bundles.php in Symfony.

https://github.com/symfony/http-kernel/blame/master/Kernel.php implements:
```
protected function initializeBundles()
    {
        // init bundles
        $this->bundles = [];
        foreach ($this->registerBundles() as $bundle) {
            $name = $bundle->getName();
            if (isset($this->bundles[$name])) {
                throw new \LogicException(sprintf('Trying to register two bundles with the same name "%s".', $name));
            }
            $this->bundles[$name] = $bundle;
        }
    }
```
Method getName() is not existing in composer/ca-bundle. This leads to
**Attempted to call an undefined method named "getName" of class "Composer\CaBundle\CaBundle".** on "dev" environment.

**Comment by Seldaek** [comment]
This CaBundle class has nothing to do with symfony or symfony bundles. It therefore does not implement the interface.

It's called bundle because it is a bundle of certificate authorities. bundle just means `a collection of things or quantity of material tied or wrapped up together.`, it does not mean "put it in your symfony kernel and see what happens".

**Comment by RicoFactset** [comment]
Hi Seldaek, yes I know. But Composer still adds to bundles.php 

**Composer\CaBundle\CaBundle::class => ['dev' => true, 'test' => true],**

after "composer install" which outputs:
**Configuring composer/ca-bundle (>=1.2.7): From auto-generated recipe**

Removing that entry from bundles.php manually solves that issue.

But still, I wonder why Composer adds that entry to bundles.php which causes the error finally.

**Comment by Seldaek** [comment]
Composer does not do anything. Some symfony integration / flex or whatever plugin does this. That looks like a bug, but it's not something we can fix here. Should be reported on flex or in symfony recipes. I am not sure what is responsible for this.

**Comment by RicoFactset** [comment]
Ok thanks, that makes then sense.

**Comment by Seldaek** [comment]
Seems to be https://github.com/symfony/flex/blob/89999fdaad52cab14637709f2d2ce25835a051e6/src/SymfonyBundle.php#L78 at fault. It just checks for the Bundle ending. Probably should do more checks than that..

**Comment by RicoFactset** [comment]
Created an issue here: https://github.com/symfony/flex/issues/622
