### ISSUE TITLE
Error on composer require

### ISSUE THREAD

**Issue by SebHoremans** [composer/ca-bundle#58]
Hello everyone,
I reach an error when installing ca-bundle. 
![image](https://user-images.githubusercontent.com/27858859/82651290-3cb91000-9c1c-11ea-948f-86cb028d25d5.png)

Thanks for your job

**Comment by GrahamCampbell** [comment]
This is a bug in Symfony, not composer. Please close this.

**Comment by SebHoremans** [comment]
In fact I this that is a compatibility problem with Symfony 5.
If you modify the class like this : 
![image](https://user-images.githubusercontent.com/27858859/82655253-32017980-9c22-11ea-82cb-6518e8d8bf43.png)
It works well.

**Comment by GrahamCampbell** [comment]
That would not be the correct fix.

**Comment by GrahamCampbell** [comment]
This package doesn't and depend on symfony's http kernel.

**Comment by GrahamCampbell** [comment]
As I said, this is a bug in Symfony, and has already been discussed. Please check existing issues before posting duplicates.

**Comment by SebHoremans** [comment]
Sorry about that. How do I get ca-bundle to work in my Symfony?

**Comment by SebHoremans** [comment]
All right, thanks for your help and for your sympathy, have a nice day.
